/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lora.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "lora.pb-c.h"
void   lo_ra_frame__init
                     (LoRaFrame         *message)
{
  static const LoRaFrame init_value = LO_RA_FRAME__INIT;
  *message = init_value;
}
size_t lo_ra_frame__get_packed_size
                     (const LoRaFrame *message)
{
  assert(message->base.descriptor == &lo_ra_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lo_ra_frame__pack
                     (const LoRaFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lo_ra_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lo_ra_frame__pack_to_buffer
                     (const LoRaFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lo_ra_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoRaFrame *
       lo_ra_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoRaFrame *)
     protobuf_c_message_unpack (&lo_ra_frame__descriptor,
                                allocator, len, data);
}
void   lo_ra_frame__free_unpacked
                     (LoRaFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lo_ra_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lo_ra_command__init
                     (LoRaCommand         *message)
{
  static const LoRaCommand init_value = LO_RA_COMMAND__INIT;
  *message = init_value;
}
size_t lo_ra_command__get_packed_size
                     (const LoRaCommand *message)
{
  assert(message->base.descriptor == &lo_ra_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lo_ra_command__pack
                     (const LoRaCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lo_ra_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lo_ra_command__pack_to_buffer
                     (const LoRaCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lo_ra_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoRaCommand *
       lo_ra_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoRaCommand *)
     protobuf_c_message_unpack (&lo_ra_command__descriptor,
                                allocator, len, data);
}
void   lo_ra_command__free_unpacked
                     (LoRaCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lo_ra_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor lo_ra_frame__field_descriptors[23] =
{
  {
    "tanWaState",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, tanwastate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressureSensor",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, pressuresensor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solenoid_fill",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, solenoid_fill),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solenoid_depr",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, solenoid_depr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "abortButton",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, abortbutton),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "igniterContinouity_1",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, ignitercontinouity_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "igniterContinouity_2",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, ignitercontinouity_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hxRequest_RCK",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, hxrequest_rck),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hxRequest_TANK",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, hxrequest_tank),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vbat",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, vbat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motorState_1",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, motorstate_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motorState_2",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, motorstate_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motorState_3",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, motorstate_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motorState_4",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, motorstate_4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rocketWeight_temp",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, rocketweight_temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tankWeight_temp",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, tankweight_temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rocketWeight_val",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, rocketweight_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tankWeight_val",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, tankweight_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rocketWeightRaw_val",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, rocketweightraw_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tankWeightRaw_val",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, tankweightraw_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_rck",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, interface_rck),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_tank",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, interface_tank),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_mcu",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoRaFrame, interface_mcu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lo_ra_frame__field_indices_by_name[] = {
  4,   /* field[4] = abortButton */
  7,   /* field[7] = hxRequest_RCK */
  8,   /* field[8] = hxRequest_TANK */
  5,   /* field[5] = igniterContinouity_1 */
  6,   /* field[6] = igniterContinouity_2 */
  22,   /* field[22] = interface_mcu */
  20,   /* field[20] = interface_rck */
  21,   /* field[21] = interface_tank */
  10,   /* field[10] = motorState_1 */
  11,   /* field[11] = motorState_2 */
  12,   /* field[12] = motorState_3 */
  13,   /* field[13] = motorState_4 */
  1,   /* field[1] = pressureSensor */
  18,   /* field[18] = rocketWeightRaw_val */
  14,   /* field[14] = rocketWeight_temp */
  16,   /* field[16] = rocketWeight_val */
  3,   /* field[3] = solenoid_depr */
  2,   /* field[2] = solenoid_fill */
  0,   /* field[0] = tanWaState */
  19,   /* field[19] = tankWeightRaw_val */
  15,   /* field[15] = tankWeight_temp */
  17,   /* field[17] = tankWeight_val */
  9,   /* field[9] = vbat */
};
static const ProtobufCIntRange lo_ra_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor lo_ra_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoRaFrame",
  "LoRaFrame",
  "LoRaFrame",
  "",
  sizeof(LoRaFrame),
  23,
  lo_ra_frame__field_descriptors,
  lo_ra_frame__field_indices_by_name,
  1,  lo_ra_frame__number_ranges,
  (ProtobufCMessageInit) lo_ra_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lo_ra_command__field_descriptors[4] =
{
  {
    "lora_dev_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaCommand, lora_dev_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sys_dev_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaCommand, sys_dev_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoRaCommand, command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LoRaCommand, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lo_ra_command__field_indices_by_name[] = {
  2,   /* field[2] = command */
  0,   /* field[0] = lora_dev_id */
  3,   /* field[3] = payload */
  1,   /* field[1] = sys_dev_id */
};
static const ProtobufCIntRange lo_ra_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor lo_ra_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoRaCommand",
  "LoRaCommand",
  "LoRaCommand",
  "",
  sizeof(LoRaCommand),
  4,
  lo_ra_command__field_descriptors,
  lo_ra_command__field_indices_by_name,
  1,  lo_ra_command__number_ranges,
  (ProtobufCMessageInit) lo_ra_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
