/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lora.proto */

#ifndef PROTOBUF_C_lora_2eproto__INCLUDED
#define PROTOBUF_C_lora_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct LoRaFrame LoRaFrame;
typedef struct LoRaCommand LoRaCommand;


/* --- enums --- */


/* --- messages --- */

struct  LoRaFrame
{
  ProtobufCMessage base;
  /*
   * tanwa frame
   */
  uint32_t tanwastate;
  uint32_t pressuresensor;
  uint32_t solenoid_fill;
  uint32_t solenoid_depr;
  protobuf_c_boolean abortbutton;
  protobuf_c_boolean ignitercontinouity_1;
  protobuf_c_boolean ignitercontinouity_2;
  /*
   * arduino string
   */
  uint32_t hxrequest_rck;
  /*
   * arduino string
   */
  uint32_t hxrequest_tank;
  float vbat;
  uint32_t motorstate_1;
  uint32_t motorstate_2;
  uint32_t motorstate_3;
  uint32_t motorstate_4;
  float rocketweight_temp;
  float tankweight_temp;
  float rocketweight_val;
  float tankweight_val;
  uint32_t rocketweightraw_val;
  uint32_t tankweightraw_val;
  protobuf_c_boolean interface_rck;
  protobuf_c_boolean interface_tank;
  protobuf_c_boolean interface_mcu;
};
#define LO_RA_FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lo_ra_frame__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  LoRaCommand
{
  ProtobufCMessage base;
  uint32_t lora_dev_id;
  uint32_t sys_dev_id;
  uint32_t command;
  int32_t payload;
};
#define LO_RA_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lo_ra_command__descriptor) \
, 0, 0, 0, 0 }


/* LoRaFrame methods */
void   lo_ra_frame__init
                     (LoRaFrame         *message);
size_t lo_ra_frame__get_packed_size
                     (const LoRaFrame   *message);
size_t lo_ra_frame__pack
                     (const LoRaFrame   *message,
                      uint8_t             *out);
size_t lo_ra_frame__pack_to_buffer
                     (const LoRaFrame   *message,
                      ProtobufCBuffer     *buffer);
LoRaFrame *
       lo_ra_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lo_ra_frame__free_unpacked
                     (LoRaFrame *message,
                      ProtobufCAllocator *allocator);
/* LoRaCommand methods */
void   lo_ra_command__init
                     (LoRaCommand         *message);
size_t lo_ra_command__get_packed_size
                     (const LoRaCommand   *message);
size_t lo_ra_command__pack
                     (const LoRaCommand   *message,
                      uint8_t             *out);
size_t lo_ra_command__pack_to_buffer
                     (const LoRaCommand   *message,
                      ProtobufCBuffer     *buffer);
LoRaCommand *
       lo_ra_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lo_ra_command__free_unpacked
                     (LoRaCommand *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LoRaFrame_Closure)
                 (const LoRaFrame *message,
                  void *closure_data);
typedef void (*LoRaCommand_Closure)
                 (const LoRaCommand *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor lo_ra_frame__descriptor;
extern const ProtobufCMessageDescriptor lo_ra_command__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_lora_2eproto__INCLUDED */
